name = "grabdeals"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat_v2"]
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DB"
database_name = "grabdeals"
database_id = "148f61c0-328a-4e7e-92d5-a9f87584cf2b"
