name = "estore-db-worker"
main = "src/worker.ts"
compatibility_date = "2024-01-01"

# NOTE: Replace 'database_id' with your actual D1 database ID after creating it
[[d1_databases]]
binding = "DB"
database_name = "grabdeals"
database_id = "148f61c0-328a-4e7e-92d5-a9f87584cf2b"

[observability]
enabled = true
