"use client"

import { useState, useRef, useEffect } from "react"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from "@/components/ui/dialog"
import {
    Loader2, Undo, Redo, Sparkles, Wand2, ArrowLeft,
    Monitor, Tablet, Smartphone, PanelLeftClose, PanelLeftOpen, Code2, Play
} from "lucide-react"
import { toast } from "@/hooks/use-toast"

export function LandingPageBuilder({
    htmlContent,
    onChange,
    productTitle,
    productPrice,
    productDescription,
    productImage,
    onSave,
    saving,
    exitLink,
    previewLink,
    isPublished,
    pageTitle,
    pageSlug,
    onTitleChange,
    storeProducts
}: any) {
    const [sidebarOpen, setSidebarOpen] = useState(true)
    const [previewMode, setPreviewMode] = useState<'desktop' | 'tablet' | 'mobile'>('desktop')

    // AI state
    const [aiModalOpen, setAiModalOpen] = useState(false)
    const [aiPrompt, setAiPrompt] = useState("")
    const [aiLoading, setAiLoading] = useState(false)
    const [selectedProduct, setSelectedProduct] = useState<any>(null)

    // Code Editor State
    const [localHtml, setLocalHtml] = useState(htmlContent || "")
    useEffect(() => {
        setLocalHtml(htmlContent || "")
    }, [htmlContent])

    const currentProduct = selectedProduct || {
        title: productTitle || pageTitle || "Product Name",
        price: productPrice || 99,
        description: productDescription || "",
        imageUrl: productImage || ""
    }

    const handleAIGenerate = async (mode: 'full' | 'edit') => {
        if (!aiPrompt.trim() && !currentProduct.title) return toast({ title: "Enter a prompt or product name first", variant: "destructive" })
        setAiLoading(true)
        try {
            const res = await fetch("/api/ai/generate-landing-page", {
                method: "POST",
                headers: { "Content-Type": "application/json" },
                body: JSON.stringify({
                    mode,
                    prompt: aiPrompt,
                    productTitle: currentProduct.title,
                    productPrice: currentProduct.price,
                    productDescription: currentProduct.description,
                    productImage: currentProduct.imageUrl || (currentProduct.images && currentProduct.images[0]) || "",
                    htmlContent: localHtml
                })
            })
            const data = await res.json()
            if (!res.ok) throw new Error(data.error || "AI generation failed")

            setLocalHtml(data.html || "")
            onChange(data.html || "")
            setAiModalOpen(false)
            setAiPrompt("")
            toast({ title: "✅ Landing page HTML generated by AI!" })
        } catch (err: any) {
            toast({ title: "AI Error", description: err.message, variant: "destructive" })
        } finally {
            setAiLoading(false)
        }
    }

    const canvasMaxWidth = previewMode === 'desktop' ? 'max-w-none' : previewMode === 'tablet' ? 'max-w-[768px]' : 'max-w-[375px]'

    return (
        <div className="flex flex-col h-screen w-full overflow-hidden bg-slate-100 relative">
            {/* ─── BUILDER TOP BAR ─── */}
            <div className="h-[60px] bg-white border-b border-gray-200 flex items-center justify-between px-4 z-30 shrink-0 shadow-sm w-full">
                <div className="flex items-center gap-4">
                    {exitLink && (
                        <Button variant="ghost" size="sm" asChild className="h-8 -ml-2 text-gray-500 hover:text-gray-900 font-semibold px-2">
                            <a href={exitLink}><ArrowLeft className="h-4 w-4 mr-1" /> Exit</a>
                        </Button>
                    )}
                    <Button onClick={() => setSidebarOpen(!sidebarOpen)} variant="ghost" size="icon" className="h-8 w-8 text-gray-500 hover:text-indigo-600 hover:bg-indigo-50 transition-colors">
                        {sidebarOpen ? <PanelLeftClose className="h-4.5 w-4.5" /> : <PanelLeftOpen className="h-4.5 w-4.5" />}
                    </Button>

                    {onTitleChange && (
                        <div className="flex items-center gap-2">
                            <div className="h-5 w-px bg-gray-200 hidden md:block" />
                            <div className="flex flex-col">
                                <Input value={pageTitle || ''} onChange={e => onTitleChange(e.target.value)}
                                    className="h-7 border-transparent hover:border-gray-200 focus:border-indigo-500 text-sm font-bold w-[200px] shadow-none px-2"
                                    placeholder="Landing Page Title" />
                                {isPublished !== undefined && (
                                    <span className={`text-[10px] font-bold px-2 uppercase tracking-wider ${isPublished ? 'text-green-600' : 'text-gray-400'}`}>
                                        {isPublished ? 'Live Published' : 'Draft'}
                                    </span>
                                )}
                            </div>
                        </div>
                    )}

                    <div className="h-5 w-px bg-gray-200 hidden md:block" />
                    <div className="hidden md:flex bg-slate-100 p-1 rounded-lg border border-gray-200">
                        <button onClick={() => setPreviewMode('desktop')} className={`p-1.5 rounded-md transition-all ${previewMode === 'desktop' ? 'bg-white shadow-sm text-indigo-600' : 'text-gray-400 hover:text-gray-600'}`}><Monitor className="h-4 w-4" /></button>
                        <button onClick={() => setPreviewMode('tablet')} className={`p-1.5 rounded-md transition-all ${previewMode === 'tablet' ? 'bg-white shadow-sm text-indigo-600' : 'text-gray-400 hover:text-gray-600'}`}><Tablet className="h-4 w-4" /></button>
                        <button onClick={() => setPreviewMode('mobile')} className={`p-1.5 rounded-md transition-all ${previewMode === 'mobile' ? 'bg-white shadow-sm text-indigo-600' : 'text-gray-400 hover:text-gray-600'}`}><Smartphone className="h-4 w-4" /></button>
                    </div>
                </div>

                <div className="flex items-center gap-2 md:gap-3">
                    {storeProducts && storeProducts.length > 0 && (
                        <div className="hidden lg:flex items-center mr-2">
                            <select
                                className="h-8 text-xs border-gray-200 rounded-md focus:border-indigo-500 focus:ring-indigo-500 bg-gray-50 font-medium text-gray-700 max-w-[150px]"
                                value={selectedProduct?.id || ''}
                                onChange={(e) => {
                                    const p = storeProducts.find((p: any) => p.id === e.target.value)
                                    setSelectedProduct(p || null)
                                }}
                            >
                                <option value="">No Product Selected</option>
                                {storeProducts.map((p: any) => <option key={p.id} value={p.id}>{p.title}</option>)}
                            </select>
                        </div>
                    )}

                    <Button size="sm" onClick={() => setAiModalOpen(true)} className="h-8 bg-black text-white hover:bg-gray-800 font-semibold text-xs border-0 px-3 shadow-sm hidden md:flex">
                        <Sparkles className="h-3.5 w-3.5 mr-1.5 text-yellow-400" /> AI Generator
                    </Button>

                    <div className="h-5 w-px bg-gray-200 hidden md:block" />

                    {previewLink && (
                        <Button variant="outline" size="sm" asChild className="h-8 hidden sm:flex text-xs font-semibold">
                            <a href={previewLink} target="_blank"><Play className="h-3.5 w-3.5 mr-1.5" /> Live View</a>
                        </Button>
                    )}
                    {onSave && (
                        <Button size="sm" onClick={() => { onChange(localHtml); onSave(localHtml); }} disabled={saving} className="h-8 bg-gradient-to-r from-violet-500 to-indigo-600 text-white font-bold text-xs px-5 shadow-md hover:shadow-lg transition-all hover:-translate-y-0.5">
                            {saving ? <><Loader2 className="h-3.5 w-3.5 animate-spin mr-1.5" /> Saving...</> : 'Save Page'}
                        </Button>
                    )}
                </div>
            </div>

            <div className="flex flex-1 overflow-hidden relative">
                {/* ─── LEFT SIDEBAR (HTML Code Editor) ─── */}
                <div className={`transition-all duration-300 ease-in-out shrink-0 border-r border-gray-200 bg-white flex flex-col h-full overflow-hidden shadow-[2px_0_8px_rgba(0,0,0,0.02)] z-20 ${sidebarOpen ? 'w-[450px] translate-x-0' : 'w-[0px] -translate-x-full border-r-0'}`}>
                    <div className="flex-1 flex flex-col w-full h-full p-4">
                        <div className="flex items-center justify-between mb-3">
                            <h3 className="text-sm font-bold text-gray-700 flex items-center gap-2">
                                <Code2 className="h-4 w-4 text-indigo-500" /> Source HTML
                            </h3>
                            <Button size="sm" variant="ghost" className="h-7 text-xs" onClick={() => onChange(localHtml)}>Update Preview</Button>
                        </div>
                        <Textarea
                            value={localHtml}
                            onChange={(e) => setLocalHtml(e.target.value)}
                            className="flex-1 font-mono text-xs resize-none bg-slate-900 text-green-400 p-4 rounded-lg shadow-inner focus-visible:ring-indigo-500 border-0 custom-scrollbar"
                            placeholder="<!-- Your Landing Page HTML goes here... -->"
                        />
                        <div className="mt-4 bg-indigo-50 rounded-lg p-3 border border-indigo-100 text-xs text-indigo-800">
                            <strong>Tip:</strong> Add a product buy button by giving it the exact ID <code>lp-buy-button</code>. 
                            Our system will automatically attach the cart logic to it.
                        </div>
                    </div>
                </div>

                {/* ─── RIGHT CANVAS (Live Preview) ─── */}
                <div className="flex-1 bg-slate-200/60 h-full overflow-y-auto relative p-4 md:p-8 custom-scrollbar flex justify-center transition-all duration-300">
                    {!localHtml ? (
                        <div className="h-full w-full flex flex-col items-center justify-center text-gray-400 space-y-4 max-w-2xl text-center">
                            <div className="h-20 w-20 bg-white shadow-xl rounded-2xl flex items-center justify-center">
                                <Sparkles className="h-8 w-8 text-indigo-300" />
                            </div>
                            <h2 className="text-xl font-bold text-gray-600">No HTML Content</h2>
                            <p className="text-sm">Write HTML code on the left, or use the AI Generator to create a beautiful page instantly.</p>
                            <Button onClick={() => setAiModalOpen(true)} className="bg-gradient-to-r from-violet-500 to-indigo-500 text-white font-bold mt-2 shadow-lg hover:shadow-xl hover:scale-105 transition-all">
                                ✨ Generate with AI
                            </Button>
                        </div>
                    ) : (
                        <div className={`w-full bg-white ${canvasMaxWidth} transition-all duration-[400ms] ease-[cubic-bezier(0.23,1,0.32,1)] shadow-2xl rounded-lg min-h-full`}>
                            {/* Injected Tailwind & Animation Context */}
                            <div className="w-full h-full lp-preview-container" dangerouslySetInnerHTML={{ __html: localHtml }} />
                        </div>
                    )}
                </div>
            </div>

            {/* ─── AI MODAL ─── */}
            <Dialog open={aiModalOpen} onOpenChange={setAiModalOpen}>
                <DialogContent className="max-w-md border-0 p-0 overflow-hidden bg-white rounded-2xl">
                    <div className="px-6 py-5 bg-gradient-to-r from-violet-500 to-indigo-600 text-white">
                        <DialogTitle className="flex items-center gap-2 text-xl font-bold text-white mb-1">
                            <Wand2 className="h-6 w-6" /> AI HTML Generator
                        </DialogTitle>
                        <DialogDescription className="text-violet-100">
                            Describe the landing page you want to create or edit. The AI will write fully responsive HTML using Tailwind CSS.
                        </DialogDescription>
                    </div>
                    <div className="p-6 space-y-4">
                        <div>
                            <label className="text-sm font-semibold text-gray-700 block mb-1">Instructions for AI</label>
                            <Textarea
                                value={aiPrompt}
                                onChange={(e) => setAiPrompt(e.target.value)}
                                placeholder="E.g. A sleek, dark-mode sales page for a fitness app. Include a hero section with a strong CTA, a features grid, and a pricing table..."
                                className="min-h-[120px] resize-none focus:ring-indigo-500 border-gray-200 custom-scrollbar"
                            />
                        </div>
                        <div className="flex gap-2 pt-2">
                            <Button onClick={() => handleAIGenerate('full')} disabled={aiLoading} className="flex-1 bg-gradient-to-r from-violet-600 to-indigo-600 hover:from-violet-700 hover:to-indigo-700 text-white font-bold shadow-md">
                                {aiLoading ? <Loader2 className="h-4 w-4 animate-spin mr-2" /> : <Sparkles className="h-4 w-4 mr-2" />}
                                Generate New Page
                            </Button>
                            {localHtml && (
                                <Button onClick={() => handleAIGenerate('edit')} disabled={aiLoading} variant="outline" className="flex-1 font-bold border-indigo-200 text-indigo-700 hover:bg-indigo-50">
                                    {aiLoading ? <Loader2 className="h-4 w-4 animate-spin mr-2" /> : <Code2 className="h-4 w-4 mr-2" />}
                                    Edit Current HTML
                                </Button>
                            )}
                        </div>
                    </div>
                </DialogContent>
            </Dialog>
        </div>
    )
}
